# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'czytnik.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_znajdzPanelWindow(object):
    def setupUi(self, znajdzPanelWindow):
        znajdzPanelWindow.setObjectName("znajdzPanelWindow")
        znajdzPanelWindow.resize(669, 538)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(znajdzPanelWindow)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 30, 251, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.info1 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.info1.setMinimumSize(QtCore.QSize(0, 50))
        self.info1.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info1.setFont(font)
        self.info1.setAlignment(QtCore.Qt.AlignCenter)
        self.info1.setObjectName("info1")
        self.verticalLayout_2.addWidget(self.info1)
        self.barCode = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.barCode.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.barCode.setFont(font)
        self.barCode.setText("")
        self.barCode.setObjectName("barCode")
        self.verticalLayout_2.addWidget(self.barCode)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clearButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.clearButton.setMinimumSize(QtCore.QSize(0, 30))
        self.clearButton.setMaximumSize(QtCore.QSize(140, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.okButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.okButton.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.okButton.setFont(font)
        self.okButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.table = QtWidgets.QTableWidget(znajdzPanelWindow)
        self.table.setGeometry(QtCore.QRect(210, 250, 256, 192))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.zamknijButton = QtWidgets.QToolButton(znajdzPanelWindow)
        self.zamknijButton.setGeometry(QtCore.QRect(550, 480, 91, 41))
        self.zamknijButton.setObjectName("zamknijButton")
        self.info2 = QtWidgets.QLabel(znajdzPanelWindow)
        self.info2.setGeometry(QtCore.QRect(210, 260, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.info2.setFont(font)
        self.info2.setText("")
        self.info2.setAlignment(QtCore.Qt.AlignCenter)
        self.info2.setObjectName("info2")

        self.retranslateUi(znajdzPanelWindow)
        self.clearButton.clicked.connect(self.barCode.clear)
        self.zamknijButton.clicked.connect(znajdzPanelWindow.close)
        QtCore.QMetaObject.connectSlotsByName(znajdzPanelWindow)

    def retranslateUi(self, znajdzPanelWindow):
        _translate = QtCore.QCoreApplication.translate
        znajdzPanelWindow.setWindowTitle(_translate("znajdzPanelWindow", "Dialog"))
        self.info1.setText(_translate("znajdzPanelWindow", "Zeskanuj kod kreskowy panelu"))
        self.clearButton.setText(_translate("znajdzPanelWindow", "Wyczyść "))
        self.okButton.setText(_translate("znajdzPanelWindow", "OK"))
        self.zamknijButton.setText(_translate("znajdzPanelWindow", "Zamknij"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    znajdzPanelWindow = QtWidgets.QDialog()
    ui = Ui_znajdzPanelWindow()
    ui.setupUi(znajdzPanelWindow)
    znajdzPanelWindow.show()
    sys.exit(app.exec_())
