# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formularz.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formularzWindow(object):
    def setupUi(self, formularzWindow):
        formularzWindow.setObjectName("formularzWindow")
        formularzWindow.resize(549, 708)
        self.centralwidget = QtWidgets.QWidget(formularzWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 80, 411, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gotowyTyp = QtWidgets.QComboBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.gotowyTyp.setFont(font)
        self.gotowyTyp.setObjectName("gotowyTyp")
        self.verticalLayout.addWidget(self.gotowyTyp)
        spacerItem = QtWidgets.QSpacerItem(0, 400, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem)
        formularzWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(formularzWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 21))
        self.menubar.setObjectName("menubar")
        formularzWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(formularzWindow)
        self.statusbar.setObjectName("statusbar")
        formularzWindow.setStatusBar(self.statusbar)

        self.retranslateUi(formularzWindow)
        QtCore.QMetaObject.connectSlotsByName(formularzWindow)

    def retranslateUi(self, formularzWindow):
        _translate = QtCore.QCoreApplication.translate
        formularzWindow.setWindowTitle(_translate("formularzWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formularzWindow = QtWidgets.QMainWindow()
    ui = Ui_formularzWindow()
    ui.setupUi(formularzWindow)
    formularzWindow.show()
    sys.exit(app.exec_())
